#!/usr/bin/env python3
import os
import sys
import argparse
import subprocess
from pathlib import Path

DEFAULT_BUILD_DIR = "build"

def cmd(arg: list[str] | str, **kwargs) -> None:
    cmd_string: str
    if type(arg) == str:
        cmd_string = arg
    else:
        cmd_string = " ".join(arg)

    print(f"Running subcommand '{cmd_string}'...")
    subprocess.run(arg, check=True, **kwargs)
    print("Success.")

def main() -> None:
    argparser = argparse.ArgumentParser(prog="test", description="Run all XMDB tests")
    argparser.add_argument("-d", "--builddir", default="./build")
    argparser.add_argument("-f", "--fail-on-snap-mismatch", action="store_true")
    argparser.add_argument("-t", "--timeout", default=60, type=int)
    args = argparser.parse_args()

    build_dir = args.builddir

    cmd(["cmake", "--build", build_dir])

    snap_files = Path(build_dir).glob("*-snap")

    for snap_test in snap_files:
        snap_test_relative = os.path.basename(str(snap_test))
        snap_file_name = f"./{snap_test_relative}"
        snap_script = "../tests/snap.py"
        snap_cmd = f"{snap_script} -f" if args.fail_on_snap_mismatch else snap_script
        cmd(f"cd build && {snap_cmd} -d ../tests/snaps {snap_file_name}", shell=True, timeout=args.timeout)

    cmd(f"cd {build_dir} && ctest", shell=True)

if __name__ == "__main__":
    main()
