#!/usr/bin/env python3
import os
import sys
import subprocess
from pathlib import Path

DEFAULT_BUILD_DIR = "build"

def cmd(arg: list[str] | str, **kwargs) -> None:
    cmd_string: str
    if type(arg) == str:
        cmd_string = arg
    else:
        cmd_string = " ".join(arg)

    print(f"Running subcommand '{cmd_string}'...")
    subprocess.run(arg, check=True, **kwargs)
    print("Success.")

def detect_build_dir() -> str:
    if os.path.exists(DEFAULT_BUILD_DIR):
        return DEFAULT_BUILD_DIR

    args = sys.argv[1:]
    if len(args) == 0:
        print("ERROR: could not determine the binary build directory and no arguments were provided")
        sys.exit(1)

    return args[0]

def main() -> None:
    build_dir = detect_build_dir()

    cmd(["cmake", "--build", build_dir])

    snap_files = Path(build_dir).glob("*-snap")

    for snap_test in snap_files:
        snap_test_relative = os.path.basename(str(snap_test))
        snap_file_name = f"./{snap_test_relative}"
        cmd(f"cd build && ../tests/snap.py -d ../tests/snaps {snap_file_name}", shell=True)

    cmd(f"cd {build_dir} && ctest", shell=True)

    cmd("cd src/WASMParser && ./build.sh", shell=True)

if __name__ == "__main__":
    main()
