name: CMake on Linux

on:
  push:
    branches: [ "production", "development" ]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'
      - '**/CMakeLists.txt'
      - '**.cmake'
  pull_request:
    branches: [ "production", "development" ]
    paths:
      - '**/*.cpp'
      - '**/*.hpp'
      - '**/*.h'
      - '**/CMakeLists.txt'
      - '**.cmake'

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Clone dependencies
      run: git submodule init && git submodule update --recursive

    - name: Setup build directory
      run: cmake -Bbuild -GNinja

    - name: Test
      working-directory: ${{github.workspace}}
      run: ./scripts/test -f

